### ISSUE TITLE
Exakat action with annotations?

### ISSUE THREAD

**Issue by arcticlinux** [exakat/exakat-ga#4]
Initially I thought that the problem with no errors being reported when output was generated from the action was an annotation issue, similar to #2. Although I discovered it was because the exit code of the action wasn't being set properly.

If like me you, in addition to it throwing an error, want annotations from where the problems occured in the code.  One method for doing that is to use the Text output format, and add a matcher for them like this: 
```yaml
    - name: Setup problem matchers for Exakat Text
      run: echo "::add-matcher::.github/exakat.json"
    - name: Exakat
      uses: docker://exakat/exakat-ga
      env:
        INPUT_EXIT_ON_ISSUES: true
      with:
        args: entrypoint.sh --format Text
```

With `.github/exakat.json` being:
```json
{
  "problemMatcher": [
    {
      "owner": "json-validator",
      "pattern": [
        {
          "regexp": "\/(.+):(\\d+)\\t(.+)\\t(.+\\t.+)$",
          "file": 1,
          "line": 2,
          "message": 4
        }
      ]
    }
  ]
}
```
